"""company_id

Revision ID: 2bf5cd25601e
Revises: 6e0463e5d95a
Create Date: 2016-08-31 09:11:32.367440

"""

# revision identifiers, used by Alembic.
revision = '2bf5cd25601e'
down_revision = '6e0463e5d95a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_id')
    ### end Alembic commands ###
