"""company_id

Revision ID: 7443ec5ef9fd
Revises: 2bf5cd25601e
Create Date: 2016-08-31 09:12:14.332354

"""

# revision identifiers, used by Alembic.
revision = '7443ec5ef9fd'
down_revision = '2bf5cd25601e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
